### ISSUE TITLE
This view can not scroll?

### ISSUE THREAD

**Issue by cmnewfan** [dinhquan/SwiftAlertView#1]
By now, i have only used this view in simulator. when i add too many buttons in the view ,it looks like this:
![simulator screen shot 2015 11 24 10 38 04](https://cloud.githubusercontent.com/assets/13043056/11356373/3552bbaa-9298-11e5-965f-973c351dfa23.png)

and i can not scroll the view to show other buttons, is there something i missed?

**Comment by dinhquan** [comment]
It's not the feature of SwiftAlerView. Generally users won't create alert view with lots of button like this.
